# Site settings
title: jorgecasas.github.io
email: jorgecasas@iternova.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jorgecasas.github.io" # the base hostname & protocol for your site
twitter_username: jorgecasas
github_username:  jorgecasas

# Build settings
markdown: kramdowni


